import React from "react";
import { storiesOf } from "@storybook/react";

import Button from "./Button.js";

storiesOf("Button", module)
  .add("Primary", () => <Button type="primary" />)
  .add("Primary Outline", () => <Button type="primary" />)
  .add("Primary Fade", () => <Button type="primary" />)
  .add("Primary Large", () => <Button type="primary" large />)
  .add("Primary Outline Large", () => <Button type="primary" large />)
  .add("Primary Fade Large", () => <Button type="primary" large />)
  .add("Danger", () => <Button type="danger" />)
  .add("Danger Outline", () => <Button type="danger" />)
  .add("Danger Fade", () => <Button type="danger" />)
  .add("Danger Large", () => <Button type="danger" large />)
  .add("Danger Large Outline", () => <Button type="danger" large />)
  .add("Danger Large Fade", () => <Button type="danger" large />)
  .add("Success", () => <Button type="success" />)
  .add("Success Outline", () => <Button type="success" />)
  .add("Success Fade", () => <Button type="success" />)
  .add("Success Large", () => <Button type="success" large />)
  .add("Success Large Outline", () => <Button type="success" large />)
  .add("Success Large Fade", () => <Button type="success" large />)
  .add("Warning", () => <Button type="warning" />)
  .add("Warning Outline", () => <Button type="warning" />)
  .add("Warning Fade", () => <Button type="warning" />)
  .add("Warning Large", () => <Button type="warning" large />)
  .add("Warning Large Outline", () => <Button type="warning" large />)
  .add("Warning Large Fade", () => <Button type="warning" large />)
  .add("Default", () => <Button type="default" />)
  .add("Default Outine", () => <Button type="default" />)
  .add("Default Fade", () => <Button type="default" />)
  .add("Default Large", () => <Button type="default" large />)
  .add("Default Large Outline", () => <Button type="default" large />)
  .add("Default Large Fade", () => <Button type="default" large />);
